<?php

namespace Plugin\EC4MOMO\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\EC4MOMO\Entity\MomoTransaction;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MomoTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MomoTransactionRepository extends AbstractRepository
{
    /**
     * MomoTransactionRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MomoTransaction::class);
    }
}
